name: Vulnerable test action

on:
  issue_comment:
    types: [created]

jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable step
        run: |
          INPUT="${{ github.event.comment.body }}"
          echo "User input:"
          echo "$INPUT"
