name: Vulnerable test action

on:
  issue_comment:
    types: [created]

jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable step
        env:
          INPUT: ${{ github.event.comment.body }}
        run: |
          echo "User input:"
          echo "$INPUT"
